version: '3'
services:
  db:
    image: postgres:latest
    network_mode: bridge
    environment:
      - POSTGRES_DB=student
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
    ports:
      - '5433:5432'